# Generated by Django 5.0.1 on 2024-02-19 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_consultation_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='index/img')),
                ('img1', models.ImageField(upload_to='index/img')),
                ('bio', models.TextField()),
                ('tutor', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('count', models.IntegerField()),
                ('numb', models.IntegerField()),
                ('slug', models.SlugField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rank', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('bio', models.TextField()),
                ('img', models.ImageField(upload_to='index/img')),
                ('phone', models.IntegerField()),
                ('slug', models.SlugField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Time_lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('lesson_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.date')),
            ],
        ),
        migrations.AddField(
            model_name='date',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.time_lesson'),
        ),
    ]
