# Generated by Django 5.0.1 on 2024-02-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_course_date_team_time_lesson_lesson_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
