# Generated by Django 5.0.1 on 2024-02-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_date_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='name',
        ),
    ]
