# Generated by Django 5.0.1 on 2024-02-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_date_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_date',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_date',
            field=models.ManyToManyField(to='blog.date'),
        ),
    ]
