# Generated by Django 5.0.1 on 2024-02-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_date_time_lesson_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_date',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='time',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_date',
            field=models.CharField(default=333, max_length=150),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Time_lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='time',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
