# Generated by Django 5.0.1 on 2024-02-19 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_lesson_lesson_date_remove_lesson_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='time',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_date',
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.time_lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_date',
            field=models.ManyToManyField(to='blog.date'),
        ),
    ]
