# Generated by Django 5.0.1 on 2024-02-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='index/img')),
                ('comment', models.TextField()),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
    ]
