# Generated by Django 5.0.1 on 2024-02-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='job',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
    ]
