# Generated by Django 5.0.1 on 2024-02-19 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_testimonial_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='count',
            new_name='month',
        ),
        migrations.RemoveField(
            model_name='course',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='numb',
        ),
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tutor',
        ),
    ]
