# Generated by Django 5.0.1 on 2024-02-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_count_course_month_remove_course_img1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='age',
        ),
        migrations.RemoveField(
            model_name='team',
            name='phone',
        ),
    ]
